### ISSUE TITLE
Issue - TaskMain.pas(77): E2012 Type of expression must be BOOLEAN

### ISSUE THREAD

**Issue by edwinyzh** [jrathlev/Delphi-WinTaskSched#1]
It's great to find this project! A little compilation error: 
```
procedure TMainForm.FormCreate(Sender: TObject);
begin
//  CoInitializeEx(nil,COINIT_MULTITHREADED);
  if TWinTaskScheduler.IsRunning then begin
    WinTasks:=TWinTaskScheduler.Create;
    if not WinTasks.Init then begin
```
Compilation stops at the above line, because `WinTasks.Init` returns HRESULT, not boolean.

The same error with Delphi XE4 and 10.2 CE.

**Comment by jrathlev** [comment]
The file was fixed on October 20
