### ISSUE TITLE
Size of handles from Windows calls when querying service status

### ISSUE THREAD

**Issue by alexsawers** [jrathlev/Delphi-WinTaskSched#10]
When querying the Task Scheduler service status the code may fail when compiled for Windows 64 bits, as it uses DWORD values to receive the handles from OpenSCManager and OpenService, and DWORD has a fixed size regardless if compiled on 32 or 64 bits. The type SC_HANDLE should be a better choice as it maps to native integers matching the size of handles returned by these Windows calls.

**Comment by jrathlev** [comment]
Fixed
