### ISSUE TITLE
Problems with "at logon" tasks

### ISSUE THREAD

**Issue by CodehunterWorks** [jrathlev/Delphi-WinTaskSched#5]
Hello!

This is a cool and very useful project! Thanks to Dr. Rathlev! 

Unfortunately I have some trouble with at-logon tasks. The demo says "Access denied" when I try to save such task and "Interface not implemented" when I run it in the IDE. 

When I run the demo with Admin privileges outside the IDE, it is able to save the task correctly (I checked it in the Win Scheduler) but it shows an error when I try to edit it again: "The trigger mode "At log on" is not supported"

Is this a known issue (I think so because there is a dedicated not-supported message)? And is there a chance to get it fixed?

Thanks
Cody

**Comment by jrathlev** [comment]
Thank you for your note. I find out that on creating at-logon triggers the LogonUserId was not specified.

I shall upload the updated code immediately.

Thanks 
JR
