### ISSUE TITLE
Range check error with Delphi 11.1

### ISSUE THREAD

**Issue by Softtouch-Software** [jrathlev/Delphi-WinTaskSched#8]
When I call CreateWinTaskScheduler(WinTasks) I get a range check error in the Wintask.ReadNextValue function in the following line:
`while sTime[k] in Numbers do inc(k)`

**Comment by Softtouch-Software** [comment]
Update:
The actual error is triggered in the function "BoundaryToTimeInfo (Boundary : string)", in the line "s:=ReadNextValue(Boundary);"
stime contains '2013-08-01T12:05:00'

**Comment by jrathlev** [comment]
This is not an issue related to the Delphi version. The exception was not raised  on my tests because range checking was disabled. 
The unit WinTask was updated by now.
